sudo: false
language: node_js
node_js:
  - "6"
  - "8"
cache:
  directories:
    - "node_modules"
    - "elm-stuff"
    - "tests/elm-stuff"
    - "tests/Doc"
notifications:
  email:
    on_success: never
    on_failure: always
