version: 2
jobs:
  test:
    docker:
      - image: ymtszw/elm_for_ci:0.18
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
          - repo-{{ .Branch }}-{{ .Revision }}
          - repo-{{ .Branch }}-
          - repo-
      - checkout
      - run: elm-verify-examples
      - run: elm-test
      - save_cache:
          paths:
            - .
          key: repo-{{ .Branch }}-{{ .Revision }}

workflows:
  version: 2
  build:
    jobs:
      - test
