version: 2
jobs:
  node6:
    docker:
      - image: circleci/node:6
    working_directory: ${HOME}/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v6-dependencies-{{ checksum "package.json" }}
          - v6-dependencies-
      - run: ./scripts/ci/ensure_libsysconfcpus.sh "$CIRCLE_WORKING_DIRECTORY"
      - run: npm install
      - save_cache:
          paths:
            - sysconfcpus
            - node_modules
            - elm-stuff
            - tests/Doc
            - tests/elm-stuff
          key: v6-dependencies-{{ checksum "package.json" }}
      - run: ./scripts/ci/replace_elm_make.sh "$CIRCLE_WORKING_DIRECTORY"
      - run: npm test
  node8:
    docker:
      - image: circleci/node:8
    working_directory: ${HOME}/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v8-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v8-dependencies-
      - run: ./scripts/ci/ensure_libsysconfcpus.sh "$CIRCLE_WORKING_DIRECTORY"
      - run: npm install
      - save_cache:
          paths:
            - sysconfcpus
            - node_modules
            - elm-stuff
            - tests/Doc
            - tests/elm-stuff
          key: v8-dependencies-{{ checksum "package.json" }}
      - run: ./scripts/ci/replace_elm_make.sh "$CIRCLE_WORKING_DIRECTORY"
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - node6
      - node8
