version: 2
jobs:
  test:
    docker:
      - image: ymtszw/elm_for_ci:0.19
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - 0.19-{{ .Branch }}-{{ .Revision }}
            - 0.19-{{ .Branch }}-
            - 0.19-
      - checkout
      - run: elm-verify-examples --elm-test=elm-test
      - run: elm-test
      - save_cache:
          paths:
            - ~/.elm
          key: 0.19-{{ .Branch }}-{{ .Revision }}

workflows:
  version: 2
  build:
    jobs:
      - test
  nightly:
    jobs:
      - test
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
